export const WALLPAPER_CATEGORIES = [
  "All",
  "Landscapes",
  "Wildlife",
  "Cityscapes",
  "Modern Architecture",
  "Abstract",
  "Minimalistic",
  "Space and Galaxies",
  "Futuristic Designs",
  "Gaming Setups",
  "Paintings",
  "Typography",
  "Black and White",
  "Inspirational Quotes",
  "Spring and Autumn",
  "Popular Movies and TV Shows",
  "Anime",
  "Cars and Bikes",
  "Sports Teams and Logos",
  "Fantasy Landscapes",
  "Pets",
];
